# Seasons by Aritzia

## 1. Skin Detection from Image

In [3]:
from numpy.core.memmap import uint8
import cv2
import numpy as np

min_range = np.array([0,133,77]np.uint8)
max_range = np.array([235,173,127],np.uint8)
image = cv2.imread("image_50.png")

In [6]:
YCRimage = cv2.cvtColor(image,cv2.COLOR_BGR2YCR_CB)
skin_area = cv2.inRange(YCRimage,min_range,max_range)
detected_skin = cv2.bitwise_and(image, image, mask = skin_area)

In [7]:
cv2.imwrite("C:\\Users\\sadie\\Pictures\\detectedImage.png", 
            np.hstack([image,detected_skin]))

True

## 2. Face Detection from Webcam

In [ ]:
import cv2
import sys
cascPath = sys.argv[1]
faceCascade = cv2.CascadeClassifier(cascPath)
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(30, 30),
        flags=cv2.cv.CV_HAAR_SCALE_IMAGE
    )

    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

## 3. Skin Detection from Webcam

## 4. Using Machine Learning to Generate Color Palettes & Product Recommendations from Skin Color

In [13]:
import pandas as pd

In [17]:
training_data1 = pd.read_csv("training_data1.csv")
training_data2 = pd.read_csv("training_data2.csv")
training_data3 = pd.read_csv("training_data3.csv")

training_data1.head(10)

  image_name skin_color
0   IMG_0001     e9d7cf
1   IMG_0002     ecd9cb
2   IMG_0003     e4dcd7
3   IMG_0004     f1dbce
4   IMG_0005     e6cbb7
5   IMG_0006     f1d9cd
6   IMG_0007     f0cdbb
7   IMG_0008     eedbd4
8   IMG_0009     e5cbbe
9   IMG_0010     ebcfce

In [18]:
training_data2.head(10)

  skin_color        season
0     e9d7cf  light_summer
1     ecd9cb  light_spring
2     e4dcd7  light_summer
3     f1dbce  light_spring
4     e6cbb7   dark autumn
5     f1d9cd   soft_summer
6     f0cdbb   true_winter
7     eedbd4   true_spring
8     e5cbbe   true_winter
9     ebcfce   soft_summer

In [19]:
training_data3.head(10)

         season product_color_r
0  light_summer            cool
1  light_spring            cool
2  light_summer            cool
3  light_spring            cool
4   dark_autumn    dark_neutral
5   soft_summer   light_neutral
6   true_winter            deep
7   true_spring          pastel
8   true_winter            deep
9   soft_summer   light_neutral

In [15]:
testing_data = pd.read_csv("testing_data.csv")

In [20]:
testing_data.head(10)

  image_name skin_color
0   IMG_0001     e7cfc7
1   IMG_0002     eccfc0
2   IMG_0003     f3d4c1
3   IMG_0004     f7ddc4
4   IMG_0005     dfbda9
5   IMG_0006     e3b3a1
6   IMG_0007     e4bea8
7   IMG_0008     e7bca0
8   IMG_0009     e5b59a
9   IMG_0010     d4a283